version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ai-workflow-db
    environment:
      POSTGRES_USER: ${DB_USER:-aiworkflow}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-aiworkflow123}
      POSTGRES_DB: ${DB_NAME:-ai_workflow}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-aiworkflow}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ai-workflow-net

  # AI Workflow System (Rust)
  ai-workflow-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-workflow-system
    depends_on:
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_started
      content-processing:
        condition: service_healthy
      knowledge-graph:
        condition: service_healthy
      realtime-communication:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${DB_USER:-aiworkflow}:${DB_PASSWORD:-aiworkflow123}@postgres:5432/${DB_NAME:-ai_workflow}
      HOST: 0.0.0.0
      PORT: 8080
      RUST_LOG: ${RUST_LOG:-info}
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-here}
      REGISTRY_ENDPOINT: http://localhost:8080
      # Microservice URLs
      CONTENT_PROCESSING_URL: ${CONTENT_PROCESSING_URL:-http://content-processing:8082}
      KNOWLEDGE_GRAPH_URL: ${KNOWLEDGE_GRAPH_URL:-http://knowledge-graph:3002}
      REALTIME_COMM_URL: ${REALTIME_COMM_URL:-http://realtime-communication:8081}
      # Monitoring
      JAEGER_ENDPOINT: ${JAEGER_ENDPOINT:-http://jaeger:14268/api/traces}
    ports:
      - "${API_PORT:-8080}:8080"
    volumes:
      - ./workflows:/app/workflows:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ai-workflow-net

  # Content Processing Microservice
  content-processing:
    build:
      context: ./services/content_processing
      dockerfile: Dockerfile
    container_name: content-processing
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${DB_USER:-aiworkflow}:${DB_PASSWORD:-aiworkflow123}@postgres:5432/${DB_NAME:-ai_workflow}
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      PORT: 8082
      RUST_LOG: ${RUST_LOG:-info}
      MAX_CONTENT_SIZE: ${MAX_CONTENT_SIZE:-10485760}
      WORKER_THREADS: ${WORKER_THREADS:-4}
    ports:
      - "${CONTENT_PROCESSING_PORT:-8082}:8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ai-workflow-net

  # Knowledge Graph Microservice  
  knowledge-graph:
    build:
      context: ./services/knowledge_graph
      dockerfile: Dockerfile
    container_name: knowledge-graph
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${DB_USER:-aiworkflow}:${DB_PASSWORD:-aiworkflow123}@postgres:5432/${DB_NAME:-ai_workflow}
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      SERVICE_PORT: 3002
      DGRAPH_HOST: ${DGRAPH_HOST:-localhost}
      DGRAPH_GRPC_PORT: ${DGRAPH_GRPC_PORT:-9080}
      DGRAPH_HTTP_PORT: ${DGRAPH_HTTP_PORT:-8080}
      RUST_LOG: ${RUST_LOG:-info}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      ENABLE_METRICS: true
    ports:
      - "${KNOWLEDGE_GRAPH_PORT:-3002}:3002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ai-workflow-net

  # Realtime Communication Microservice
  realtime-communication:
    build:
      context: ./services/realtime_communication
      dockerfile: Dockerfile
    container_name: realtime-communication
    depends_on:
      redis:
        condition: service_healthy
    environment:
      HOST: 0.0.0.0
      PORT: 8081
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-here}
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      MAX_CONNECTIONS: ${MAX_CONNECTIONS:-10000}
      HEARTBEAT_INTERVAL: ${HEARTBEAT_INTERVAL:-30s}
      CLIENT_TIMEOUT: ${CLIENT_TIMEOUT:-60s}
      RUST_LOG: ${RUST_LOG:-info}
    ports:
      - "${REALTIME_COMM_PORT:-8081}:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ai-workflow-net

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: ai-workflow-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    networks:
      - ai-workflow-net

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: ai-workflow-grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    networks:
      - ai-workflow-net

  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ai-workflow-jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - "${JAEGER_UI_PORT:-16686}:16686"  # Jaeger UI
      - "${JAEGER_COLLECTOR_PORT:-14268}:14268"  # Collector HTTP
      - "${JAEGER_QUERY_PORT:-16687}:16687"  # Query Service
      - "9411:9411"  # Zipkin compatible endpoint
    networks:
      - ai-workflow-net

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: ai-workflow-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis123}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ai-workflow-net

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: ai-workflow-nginx
    depends_on:
      - ai-workflow-system
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    networks:
      - ai-workflow-net
    profiles:
      - production

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  redis_data:

networks:
  ai-workflow-net:
    driver: bridge