global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ai-workflow-system'
    static_configs:
      - targets: ['ai-workflow-system:8080']
    metrics_path: '/metrics'
